<a href="https://colab.research.google.com/github/springboardmentor1234r/B13-AirFly-Insights-Internship/blob/Devika_S_Nair/milestone_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**AirFly Insights: Data Visualization and Analysis of Airline Operations**

***Milestone 1: Data Foundation and Cleaning***

Goal: Analyze airline delays / sales / traffic patterns

In [2]:
#Import Libraries

import pandas as pd
import numpy as np

In [11]:
#Load Dataset

df = pd.read_csv('data/Flight_Dataset.csv')

print("Initial Shape:", df.shape)
df.head()

Initial Shape: (3000000, 32)

,FL_DATE,AIRLINE,AIRLINE_DOT,AIRLINE_CODE,DOT_CODE,FL_NUMBER,ORIGIN,ORIGIN_CITY,DEST,DEST_CITY,...,DIVERTED,CRS_ELAPSED_TIME,ELAPSED_TIME,AIR_TIME,DISTANCE,DELAY_DUE_CARRIER,DELAY_DUE_WEATHER,DELAY_DUE_NAS,DELAY_DUE_SECURITY,DELAY_DUE_LATE_AIRCRAFT
0,2019-01-09,United Air Lines Inc.,United Air Lines Inc.: UA,UA,19977,1562,FLL,"Fort Lauderdale, FL",EWR,"Newark, NJ",...,0.0,186.0,176.0,153.0,1065.0,NaN,NaN,NaN,NaN,NaN
1,2022-11-19,Delta Air Lines Inc.,Delta Air Lines Inc.: DL,DL,19790,1149,MSP,"Minneapolis, MN",SEA,"Seattle, WA",...,0.0,235.0,236.0,189.0,1399.0,NaN,NaN,NaN,NaN,NaN
2,2022-07-22,United Air Lines Inc.,United Air Lines Inc.: UA,UA,19977,459,DEN,"Denver, CO",MSP,"Minneapolis, MN",...,0.0,118.0,112.0,87.0,680.0,NaN,NaN,NaN,NaN,NaN
3,2023-03-06,Delta Air Lines Inc.,Delta Air Lines Inc.: DL,DL,19790,2295,MSP,"Minneapolis, MN",SFO,"San Francisco, CA",...,0.0,260.0,285.0,249.0,1589.0,0.0,0.0,24.0,0.0,0.0
4,2020-02-23,Spirit Air Lines,Spirit Air Lines: NK,NK,20416,407,MCO,"Orlando, FL",DFW,"Dallas/Fort Worth, TX",...,0.0,181.0,182.0,153.0,985.0,NaN,NaN,NaN,NaN,NaN

In [13]:
#Data Understanding

pd.set_option('display.max_columns', 40)

print("\nColumns:\n", df.columns)
print("\nData Info:")
df.info()

print("\nSummary Statistics:")
df.describe()

Columns:
 Index(['FL_DATE', 'AIRLINE', 'AIRLINE_DOT', 'AIRLINE_CODE', 'DOT_CODE',
       'FL_NUMBER', 'ORIGIN', 'ORIGIN_CITY', 'DEST', 'DEST_CITY',
       'CRS_DEP_TIME', 'DEP_TIME', 'DEP_DELAY', 'TAXI_OUT', 'WHEELS_OFF',
       'WHEELS_ON', 'TAXI_IN', 'CRS_ARR_TIME', 'ARR_TIME', 'ARR_DELAY',
       'CANCELLED', 'CANCELLATION_CODE', 'DIVERTED', 'CRS_ELAPSED_TIME',
       'ELAPSED_TIME', 'AIR_TIME', 'DISTANCE', 'DELAY_DUE_CARRIER',
       'DELAY_DUE_WEATHER', 'DELAY_DUE_NAS', 'DELAY_DUE_SECURITY',
       'DELAY_DUE_LATE_AIRCRAFT'],
      dtype='str')

Data Info:
<class 'pandas.DataFrame'>
RangeIndex: 3000000 entries, 0 to 2999999
Data columns (total 32 columns):
 #   Column                   Dtype
---  ------                   -----
 0   FL_DATE                  str
 1   AIRLINE                  str
 2   AIRLINE_DOT              str
 3   AIRLINE_CODE             str
 4   DOT_CODE                 int64
 5   FL_NUMBER                int64
 6   ORIGIN                   str
 7   ORIGIN_CITY              str
 8   DEST                     str
 9   DEST_CITY                str
 10  CRS_DEP_TIME             int64
 11  DEP_TIME                 float64
 12  DEP_DELAY                float64
 13  TAXI_OUT                 float64
 14  WHEELS_OFF               float64
 15  WHEELS_ON                float64
 16  TAXI_IN                  float64
 17  CRS_ARR_TIME             int64
 18  ARR_TIME                 float64
 19  ARR_DELAY                float64
 20  CANCELLED                float64
 21  CANCELLATION_CODE        str
 22  DIVERTED                 float64
 23  CRS_ELAPSED_TIME         float64
 24  ELAPSED_TIME             float64
 25  AIR_TIME                 float64
 26  DISTANCE                 float64
 27  DELAY_DUE_CARRIER        float64
 28  DELAY_DUE_WEATHER        float64
 29  DELAY_DUE_NAS            float64
 30  DELAY_DUE_SECURITY       float64
 31  DELAY_DUE_LATE_AIRCRAFT  float64
dtypes: float64(19), int64(4), str(9)
memory usage: 732.4 MB

Summary Statistics:

,DOT_CODE,FL_NUMBER,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,TAXI_OUT,WHEELS_OFF,WHEELS_ON,TAXI_IN,CRS_ARR_TIME,ARR_TIME,ARR_DELAY,CANCELLED,DIVERTED,CRS_ELAPSED_TIME,ELAPSED_TIME,AIR_TIME,DISTANCE,DELAY_DUE_CARRIER,DELAY_DUE_WEATHER,DELAY_DUE_NAS,DELAY_DUE_SECURITY,DELAY_DUE_LATE_AIRCRAFT
count,3.000000e+06,3.000000e+06,3.000000e+06,2.922385e+06,2.922356e+06,2.921194e+06,2.921194e+06,2.920056e+06,2.920056e+06,3.000000e+06,2.920058e+06,2.913802e+06,3.000000e+06,3.000000e+06,2.999986e+06,2.913802e+06,2.913802e+06,3.000000e+06,533863.000000,533863.000000,533863.000000,533863.000000,533863.000000
mean,1.997629e+04,2.511536e+03,1.327062e+03,1.329776e+03,1.012333e+01,1.664305e+01,1.352361e+03,1.462500e+03,7.678982e+00,1.490561e+03,1.466511e+03,4.260858e+00,2.638000e-02,2.352000e-03,1.422758e+02,1.366205e+02,1.123108e+02,8.093616e+02,24.759086,3.985260,13.164728,0.145931,25.471282
std,3.772846e+02,1.747258e+03,4.858789e+02,4.993101e+02,4.925183e+01,9.192901e+00,5.008727e+02,5.272368e+02,6.269639e+00,5.115476e+02,5.318383e+02,5.117482e+01,1.602626e-01,4.844036e-02,7.155669e+01,7.167582e+01,6.975484e+01,5.878939e+02,71.771845,32.410796,33.161122,3.582053,55.766892
min,1.939300e+04,1.000000e+00,1.000000e+00,1.000000e+00,-9.000000e+01,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,-9.600000e+01,0.000000e+00,0.000000e+00,1.000000e+00,1.500000e+01,8.000000e+00,2.900000e+01,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.979000e+04,1.051000e+03,9.150000e+02,9.160000e+02,-6.000000e+00,1.100000e+01,9.310000e+02,1.049000e+03,4.000000e+00,1.107000e+03,1.053000e+03,-1.600000e+01,0.000000e+00,0.000000e+00,9.000000e+01,8.400000e+01,6.100000e+01,3.770000e+02,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1.993000e+04,2.152000e+03,1.320000e+03,1.323000e+03,-2.000000e+00,1.400000e+01,1.336000e+03,1.501000e+03,6.000000e+00,1.516000e+03,1.505000e+03,-7.000000e+00,0.000000e+00,0.000000e+00,1.250000e+02,1.200000e+02,9.500000e+01,6.510000e+02,4.000000,0.000000,0.000000,0.000000,0.000000
75%,2.036800e+04,3.797000e+03,1.730000e+03,1.739000e+03,6.000000e+00,1.900000e+01,1.752000e+03,1.908000e+03,9.000000e+00,1.919000e+03,1.913000e+03,7.000000e+00,0.000000e+00,0.000000e+00,1.720000e+02,1.670000e+02,1.420000e+02,1.046000e+03,23.000000,0.000000,17.000000,0.000000,30.000000
max,2.045200e+04,9.562000e+03,2.359000e+03,2.400000e+03,2.966000e+03,1.840000e+02,2.400000e+03,2.400000e+03,2.490000e+02,2.400000e+03,2.400000e+03,2.934000e+03,1.000000e+00,1.000000e+00,7.050000e+02,7.390000e+02,6.920000e+02,5.812000e+03,2934.000000,1653.000000,1741.000000,1185.000000,2557.000000

In [15]:
#Duplicate Check

print("\nDuplicate Rows:", df.duplicated().sum())

Duplicate Rows: 0

In [17]:
#Missing Values Analysis

print("\nMissing Values:\n")
print(df.isnull().sum())

Missing Values:

FL_DATE                          0
AIRLINE                          0
AIRLINE_DOT                      0
AIRLINE_CODE                     0
DOT_CODE                         0
FL_NUMBER                        0
ORIGIN                           0
ORIGIN_CITY                      0
DEST                             0
DEST_CITY                        0
CRS_DEP_TIME                     0
DEP_TIME                     77615
DEP_DELAY                    77644
TAXI_OUT                     78806
WHEELS_OFF                   78806
WHEELS_ON                    79944
TAXI_IN                      79944
CRS_ARR_TIME                     0
ARR_TIME                     79942
ARR_DELAY                    86198
CANCELLED                        0
CANCELLATION_CODE          2920860
DIVERTED                         0
CRS_ELAPSED_TIME                14
ELAPSED_TIME                 86198
AIR_TIME                     86198
DISTANCE                         0
DELAY_DUE_CARRIER          2466137
DELAY_DUE_WEATHER          2466137
DELAY_DUE_NAS              2466137
DELAY_DUE_SECURITY         2466137
DELAY_DUE_LATE_AIRCRAFT    2466137
dtype: int64

In [19]:
#Understanding Nulls (Important Insight)

print("\nSample rows where DEP_TIME is NULL:")
print(df[df['DEP_TIME'].isnull()].head())

Sample rows where DEP_TIME is NULL:
        FL_DATE                 AIRLINE                 AIRLINE_DOT  \
14   2020-04-07  Southwest Airlines Co.  Southwest Airlines Co.: WN
45   2022-01-02        Republic Airline        Republic Airline: YX
80   2020-04-20  Southwest Airlines Co.  Southwest Airlines Co.: WN
191  2021-12-31    Alaska Airlines Inc.    Alaska Airlines Inc.: AS
236  2020-04-14  Southwest Airlines Co.  Southwest Airlines Co.: WN

    AIRLINE_CODE  DOT_CODE  FL_NUMBER ORIGIN     ORIGIN_CITY DEST  \
14            WN     19393        687    SJC    San Jose, CA  LAX
45            YX     20452       3467    ORD     Chicago, IL  DCA
80            WN     19393        246    BNA   Nashville, TN  ATL
191           AS     19930       1097    IAD  Washington, DC  LAX
236           WN     19393        446    LAS   Las Vegas, NV  HOU

           DEST_CITY  CRS_DEP_TIME  DEP_TIME  DEP_DELAY  TAXI_OUT  WHEELS_OFF  \
14   Los Angeles, CA          2155       NaN        NaN       NaN         NaN
45    Washington, DC          1935       NaN        NaN       NaN         NaN
80       Atlanta, GA          1055       NaN        NaN       NaN         NaN
191  Los Angeles, CA          1720       NaN        NaN       NaN         NaN
236      Houston, TX           500       NaN        NaN       NaN         NaN

     WHEELS_ON  TAXI_IN  CRS_ARR_TIME  ARR_TIME  ARR_DELAY  CANCELLED  \
14         NaN      NaN          2315       NaN        NaN        1.0
45         NaN      NaN          2241       NaN        NaN        1.0
80         NaN      NaN          1300       NaN        NaN        1.0
191        NaN      NaN          2024       NaN        NaN        1.0
236        NaN      NaN           955       NaN        NaN        1.0

    CANCELLATION_CODE  DIVERTED  CRS_ELAPSED_TIME  ELAPSED_TIME  AIR_TIME  \
14                  D       0.0              80.0           NaN       NaN
45                  B       0.0             126.0           NaN       NaN
80                  D       0.0              65.0           NaN       NaN
191                 A       0.0             364.0           NaN       NaN
236                 D       0.0             175.0           NaN       NaN

     DISTANCE  DELAY_DUE_CARRIER  DELAY_DUE_WEATHER  DELAY_DUE_NAS  \
14      308.0                NaN                NaN            NaN
45      612.0                NaN                NaN            NaN
80      214.0                NaN                NaN            NaN
191    2288.0                NaN                NaN            NaN
236    1235.0                NaN                NaN            NaN

     DELAY_DUE_SECURITY  DELAY_DUE_LATE_AIRCRAFT
14                  NaN                      NaN
45                  NaN                      NaN
80                  NaN                      NaN
191                 NaN                      NaN
236                 NaN                      NaN

In [21]:
#Handling Cancellation Code

# Flights not cancelled → NaN in cancellation_code
df['CANCELLATION_CODE'] = df['CANCELLATION_CODE'].fillna('NC')

In [23]:
#Removing Invalid CRS_ELAPSED_TIME

df.dropna(subset=['CRS_ELAPSED_TIME'], inplace=True)

In [25]:
#Handling Delay Columns (Major Logic)

delays = [
    'DELAY_DUE_CARRIER', 'DELAY_DUE_WEATHER',
    'DELAY_DUE_NAS', 'DELAY_DUE_SECURITY',
    'DELAY_DUE_LATE_AIRCRAFT'
]

In [27]:
#Flights arrived early/on-time → delay = 0
mask = (
    (df['CANCELLATION_CODE'] == 'NC') &
    (df['DIVERTED'] == 0) &
    (df['ARR_DELAY'] <= 0)
)

df.loc[mask, delays] = df.loc[mask, delays].fillna(0.0)

In [29]:
#Investigating Operational Nulls

print("\nDEP_TIME NULL Analysis:")
print(df[df['DEP_TIME'].isna()][['CANCELLED','DIVERTED']].value_counts())

print("\nTAXI_IN NULL Analysis:")
print(df[df['TAXI_IN'].isna()][['CANCELLED','DIVERTED']].value_counts())

DEP_TIME NULL Analysis:
CANCELLED  DIVERTED
1.0        0.0         77602
Name: count, dtype: int64

TAXI_IN NULL Analysis:
CANCELLED  DIVERTED
1.0        0.0         79126
0.0        1.0           802
           0.0             2
Name: count, dtype: int64

In [33]:
#Removing Logical Errors

invalid_rows = df[
    (df['TAXI_IN'].isna()) &
    (df['CANCELLED'] == 0) &
    (df['DIVERTED'] == 0)
]

print("\nInvalid Rows Removed:", invalid_rows.shape)

df = df.drop(invalid_rows.index)

Invalid Rows Removed: (0, 32)

In [35]:
#Handling Minor Delays (<=15 mins)

mask1 = (
    (df['CANCELLED'] == 0) &
    (df['DIVERTED'] == 0) &
    (df['ARR_DELAY'] <= 15)
)

df.loc[mask1, delays] = df.loc[mask1, delays].fillna(0.0)

In [37]:
#Final Missing Values Check

print("\nRemaining Null Values:\n")
print(df.isnull().sum())

Remaining Null Values:

FL_DATE                        0
AIRLINE                        0
AIRLINE_DOT                    0
AIRLINE_CODE                   0
DOT_CODE                       0
FL_NUMBER                      0
ORIGIN                         0
ORIGIN_CITY                    0
DEST                           0
DEST_CITY                      0
CRS_DEP_TIME                   0
DEP_TIME                   77602
DEP_DELAY                  77630
TAXI_OUT                   78792
WHEELS_OFF                 78792
WHEELS_ON                  79928
TAXI_IN                    79928
CRS_ARR_TIME                   0
ARR_TIME                   79926
ARR_DELAY                  86182
CANCELLED                      0
CANCELLATION_CODE              0
DIVERTED                       0
CRS_ELAPSED_TIME               0
ELAPSED_TIME               86182
AIR_TIME                   86182
DISTANCE                       0
DELAY_DUE_CARRIER          86182
DELAY_DUE_WEATHER          86182
DELAY_DUE_NAS              86182
DELAY_DUE_SECURITY         86182
DELAY_DUE_LATE_AIRCRAFT    86182
dtype: int64

In [39]:
#Extra Validation (ADDED)

print("\nFlights with Negative Arrival Delay (Early Arrival):")
print(df[df['ARR_DELAY'] < 0].shape)

print("\nFlights with Extreme Delay (>1000 mins):")
print(df[df['ARR_DELAY'] > 1000].shape)

Flights with Negative Arrival Delay (Early Arrival):
(1881970, 32)

Flights with Extreme Delay (>1000 mins):
(892, 32)

In [41]:
#Data Type Conversion

df['FL_DATE'] = pd.to_datetime(df['FL_DATE'])

df['CANCELLED'] = df['CANCELLED'].astype('int8')
df['DIVERTED'] = df['DIVERTED'].astype('int8')

cat_cols = [
    'AIRLINE','AIRLINE_DOT','AIRLINE_CODE',
    'ORIGIN','ORIGIN_CITY','DEST','DEST_CITY',
    'CANCELLATION_CODE'
]

for col in cat_cols:
    df[col] = df[col].astype('category')


# Convert float columns
minu_cols = [
    'DEP_DELAY','ARR_DELAY','TAXI_IN','TAXI_OUT',
    'CRS_ELAPSED_TIME','ELAPSED_TIME','AIR_TIME',
    'DELAY_DUE_CARRIER','DELAY_DUE_WEATHER',
    'DELAY_DUE_NAS','DELAY_DUE_SECURITY',
    'DELAY_DUE_LATE_AIRCRAFT'
]

for col in minu_cols:
    df[col] = df[col].astype('float32')


# Convert time columns
time_cols = [
    'CRS_DEP_TIME','DEP_TIME','CRS_ARR_TIME',
    'ARR_TIME','WHEELS_OFF','WHEELS_ON'
]

for col in time_cols:
    df[col] = df[col].astype('Int32')


# Optimize numeric columns
df['DISTANCE'] = df['DISTANCE'].astype('float32')
df['DOT_CODE'] = df['DOT_CODE'].astype('int32')
df['FL_NUMBER'] = df['FL_NUMBER'].astype('int32')

In [43]:
#Feature Engineering

df['YEAR'] = df['FL_DATE'].dt.year.astype('int32')
df['MONTH'] = df['FL_DATE'].dt.month.astype('int8')
df['MONTH_NAME'] = df['FL_DATE'].dt.month_name().astype('category')
df['WEEKDAY'] = df['FL_DATE'].dt.day_name().astype('category')

# Departure Hour
df['DEP_HOUR'] = df['DEP_TIME'] // 100
df['DEP_HOUR'] = df['DEP_HOUR'].fillna(df['CRS_DEP_TIME'] // 100)
df['DEP_HOUR'] = df['DEP_HOUR'].astype('Int8')

# Route Column
df['ROUTE'] = (df['ORIGIN'].astype(str) + '-' + df['DEST'].astype(str)).astype('category')

In [45]:
#Additional Features

# Delay Category
df['DELAY_STATUS'] = pd.cut(
    df['ARR_DELAY'],
    bins=[-1000, 0, 15, 60, 180, 10000],
    labels=['Early', 'On-Time', 'Minor Delay', 'Moderate Delay', 'Severe Delay']
)

# Weekend Indicator
df['IS_WEEKEND'] = df['WEEKDAY'].isin(['Saturday','Sunday']).astype('int8')

In [47]:
#Final Dataset Info

print("\nFinal Shape:", df.shape)
df.info()

Final Shape: (2999984, 40)
<class 'pandas.DataFrame'>
Index: 2999984 entries, 0 to 2999999
Data columns (total 40 columns):
 #   Column                   Dtype
---  ------                   -----
 0   FL_DATE                  datetime64[us]
 1   AIRLINE                  category
 2   AIRLINE_DOT              category
 3   AIRLINE_CODE             category
 4   DOT_CODE                 int32
 5   FL_NUMBER                int32
 6   ORIGIN                   category
 7   ORIGIN_CITY              category
 8   DEST                     category
 9   DEST_CITY                category
 10  CRS_DEP_TIME             Int32
 11  DEP_TIME                 Int32
 12  DEP_DELAY                float32
 13  TAXI_OUT                 float32
 14  WHEELS_OFF               Int32
 15  WHEELS_ON                Int32
 16  TAXI_IN                  float32
 17  CRS_ARR_TIME             Int32
 18  ARR_TIME                 Int32
 19  ARR_DELAY                float32
 20  CANCELLED                int8
 21  CANCELLATION_CODE        category
 22  DIVERTED                 int8
 23  CRS_ELAPSED_TIME         float32
 24  ELAPSED_TIME             float32
 25  AIR_TIME                 float32
 26  DISTANCE                 float32
 27  DELAY_DUE_CARRIER        float32
 28  DELAY_DUE_WEATHER        float32
 29  DELAY_DUE_NAS            float32
 30  DELAY_DUE_SECURITY       float32
 31  DELAY_DUE_LATE_AIRCRAFT  float32
 32  YEAR                     int32
 33  MONTH                    int8
 34  MONTH_NAME               category
 35  WEEKDAY                  category
 36  DEP_HOUR                 Int8
 37  ROUTE                    category
 38  DELAY_STATUS             category
 39  IS_WEEKEND               int8
dtypes: Int32(6), Int8(1), category(12), datetime64[us](1), float32(13), int32(3), int8(4)
memory usage: 380.6 MB

In [49]:
#KPI Calculations

total_flights = len(df)
unique_airlines = df['AIRLINE'].nunique()

cancelled_pct = (df['CANCELLED'].sum() / total_flights) * 100
diverted_pct = (df['DIVERTED'].sum() / total_flights) * 100

late_departure_pct = (
    (df['DEP_DELAY'] > 0).sum() /
    df['DEP_DELAY'].notna().sum()
) * 100

avg_dep_delay = df[(df['DEP_DELAY'] > 0) & (df['CANCELLED'] == 0)]['DEP_DELAY'].mean()
avg_arr_delay = df[(df['ARR_DELAY'] > 0) & (df['CANCELLED'] == 0)]['ARR_DELAY'].mean()

In [51]:
#KPI Output

print("\n========== KPI SUMMARY ==========")
print("Total Flights:", total_flights)
print("Unique Airlines:", unique_airlines)
print(f"Cancelled Flights: {cancelled_pct:.2f}%")
print(f"Diverted Flights: {diverted_pct:.2f}%")
print(f"Late Departures: {late_departure_pct:.2f}%")
print(f"Avg Departure Delay: {avg_dep_delay:.2f} mins")
print(f"Avg Arrival Delay: {avg_arr_delay:.2f} mins")

========== KPI SUMMARY ==========
Total Flights: 2999984
Unique Airlines: 18
Cancelled Flights: 2.64%
Diverted Flights: 0.24%
Late Departures: 33.97%
Avg Departure Delay: 39.46 mins
Avg Arrival Delay: 39.75 mins

In [52]:
#Save Cleaned Dataset

df.to_csv('cleaned_flights_sample_final.csv', index=False)

print("\n✅ Dataset saved successfully!")

✅ Dataset saved successfully!