# *Infosys Springboard Internship 6.0*

# Milestone-1

# AirFly Insights – Airline Operations Analysis

This project analyzes airline flight data to understand patterns in flight delays, cancellations, and operational performance. The goal is to prepare the dataset for further visualization and analysis by performing data cleaning, preprocessing, and feature engineering.

## Objective

The objective of Milestone 1 is to:

• Load the airline dataset  
• Understand the dataset structure  
• Identify missing values  
• Perform data cleaning  
• Create useful derived features  
• Save the cleaned dataset for future analysis

# Data Foundation and Cleaning

In [ ]:
# Import Libraries
import pandas as pd              #  Pandas is used for data manipulation, NumPy for numerical operations, and Matplotlib/Seaborn for visualization
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load Dataset
df = pd.read_csv("/content/drive/MyDrive/CA-2/flights_sample_3m.csv")   #  The dataset was loaded into a Pandas DataFrame for analysis.
df.head()

,FL_DATE,AIRLINE,AIRLINE_DOT,AIRLINE_CODE,DOT_CODE,FL_NUMBER,ORIGIN,ORIGIN_CITY,DEST,DEST_CITY,...,DIVERTED,CRS_ELAPSED_TIME,ELAPSED_TIME,AIR_TIME,DISTANCE,DELAY_DUE_CARRIER,DELAY_DUE_WEATHER,DELAY_DUE_NAS,DELAY_DUE_SECURITY,DELAY_DUE_LATE_AIRCRAFT
0,2019-01-09,United Air Lines Inc.,United Air Lines Inc.: UA,UA,19977,1562,FLL,"Fort Lauderdale, FL",EWR,"Newark, NJ",...,0.0,186.0,176.0,153.0,1065.0,NaN,NaN,NaN,NaN,NaN
1,2022-11-19,Delta Air Lines Inc.,Delta Air Lines Inc.: DL,DL,19790,1149,MSP,"Minneapolis, MN",SEA,"Seattle, WA",...,0.0,235.0,236.0,189.0,1399.0,NaN,NaN,NaN,NaN,NaN
2,2022-07-22,United Air Lines Inc.,United Air Lines Inc.: UA,UA,19977,459,DEN,"Denver, CO",MSP,"Minneapolis, MN",...,0.0,118.0,112.0,87.0,680.0,NaN,NaN,NaN,NaN,NaN
3,2023-03-06,Delta Air Lines Inc.,Delta Air Lines Inc.: DL,DL,19790,2295,MSP,"Minneapolis, MN",SFO,"San Francisco, CA",...,0.0,260.0,285.0,249.0,1589.0,0.0,0.0,24.0,0.0,0.0
4,2020-02-23,Spirit Air Lines,Spirit Air Lines: NK,NK,20416,407,MCO,"Orlando, FL",DFW,"Dallas/Fort Worth, TX",...,0.0,181.0,182.0,153.0,985.0,NaN,NaN,NaN,NaN,NaN

## Dataset Description

The dataset contains airline operational data including flight schedules, delays, cancellations, and route information.  
It contains approximately 3 million records and 32 columns.

Each record represents a single flight with details such as airline code, departure time, arrival time, delay causes, and distance.

***Basic Exploration***

In [ ]:
df.shape  #  The dataset contains approximately 3 million flight records and 32 columns, representing airline operations data.

(3000000, 32)

In [ ]:
df.columns  # These columns include airline information, departure and arrival times, delay details, cancellation status, and route information.

Index(['FL_DATE', 'AIRLINE', 'AIRLINE_DOT', 'AIRLINE_CODE', 'DOT_CODE',
       'FL_NUMBER', 'ORIGIN', 'ORIGIN_CITY', 'DEST', 'DEST_CITY',
       'CRS_DEP_TIME', 'DEP_TIME', 'DEP_DELAY', 'TAXI_OUT', 'WHEELS_OFF',
       'WHEELS_ON', 'TAXI_IN', 'CRS_ARR_TIME', 'ARR_TIME', 'ARR_DELAY',
       'CANCELLED', 'CANCELLATION_CODE', 'DIVERTED', 'CRS_ELAPSED_TIME',
       'ELAPSED_TIME', 'AIR_TIME', 'DISTANCE', 'DELAY_DUE_CARRIER',
       'DELAY_DUE_WEATHER', 'DELAY_DUE_NAS', 'DELAY_DUE_SECURITY',
       'DELAY_DUE_LATE_AIRCRAFT'],
      dtype='object')

In [ ]:
df.info()   #  The dataset contains numerical, categorical, and time-related features. Some columns have missing values which need to be handled.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000000 entries, 0 to 2999999
Data columns (total 32 columns):
 #   Column                   Dtype
---  ------                   -----
 0   FL_DATE                  object
 1   AIRLINE                  object
 2   AIRLINE_DOT              object
 3   AIRLINE_CODE             object
 4   DOT_CODE                 int64
 5   FL_NUMBER                int64
 6   ORIGIN                   object
 7   ORIGIN_CITY              object
 8   DEST                     object
 9   DEST_CITY                object
 10  CRS_DEP_TIME             int64
 11  DEP_TIME                 float64
 12  DEP_DELAY                float64
 13  TAXI_OUT                 float64
 14  WHEELS_OFF               float64
 15  WHEELS_ON                float64
 16  TAXI_IN                  float64
 17  CRS_ARR_TIME             int64
 18  ARR_TIME                 float64
 19  ARR_DELAY                float64
 20  CANCELLED                float64
 21  CANCELLATION_CODE        object
 22  DIVERTED                 float64
 23  CRS_ELAPSED_TIME         float64
 24  ELAPSED_TIME             float64
 25  AIR_TIME                 float64
 26  DISTANCE                 float64
 27  DELAY_DUE_CARRIER        float64
 28  DELAY_DUE_WEATHER        float64
 29  DELAY_DUE_NAS            float64
 30  DELAY_DUE_SECURITY       float64
 31  DELAY_DUE_LATE_AIRCRAFT  float64
dtypes: float64(19), int64(4), object(9)
memory usage: 732.4+ MB

In [ ]:
df.describe()    #   The summary statistics provide information about average flight times, delays, and distances.

,FL_DATE,DOT_CODE,FL_NUMBER,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,TAXI_OUT,WHEELS_OFF,WHEELS_ON,TAXI_IN,...,DELAY_DUE_WEATHER,DELAY_DUE_NAS,DELAY_DUE_SECURITY,DELAY_DUE_LATE_AIRCRAFT,DEP_HOUR,ARR_HOUR,IS_DELAYED,YEAR,MONTH,DAY
count,3000000,3.000000e+06,3.000000e+06,3.000000e+06,2.922385e+06,3.000000e+06,2.921194e+06,2.921194e+06,2.920056e+06,2.920056e+06,...,3.000000e+06,3.000000e+06,3.000000e+06,3.000000e+06,3.000000e+06,3.000000e+06,3.000000e+06,3.000000e+06,3.000000e+06,3.000000e+06
mean,2021-05-07 18:03:59.616002048,1.997629e+04,2.511536e+03,1.327062e+03,1.329776e+03,9.861321e+00,1.664305e+01,1.352361e+03,1.462500e+03,7.678982e+00,...,7.091943e-01,2.342720e+00,2.596900e-02,4.532725e+00,1.300111e+01,1.461053e+01,3.260490e-01,2.020873e+03,6.238998e+00,1.574214e+01
min,2019-01-01 00:00:00,1.939300e+04,1.000000e+00,1.000000e+00,1.000000e+00,-9.000000e+01,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.019000e+03,1.000000e+00,1.000000e+00
25%,2019-12-28 00:00:00,1.979000e+04,1.051000e+03,9.150000e+02,9.160000e+02,-6.000000e+00,1.100000e+01,9.310000e+02,1.049000e+03,4.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,9.000000e+00,1.100000e+01,0.000000e+00,2.019000e+03,3.000000e+00,8.000000e+00
50%,2021-06-28 00:00:00,1.993000e+04,2.152000e+03,1.320000e+03,1.323000e+03,-2.000000e+00,1.400000e+01,1.336000e+03,1.501000e+03,6.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.300000e+01,1.500000e+01,0.000000e+00,2.021000e+03,6.000000e+00,1.600000e+01
75%,2022-08-02 00:00:00,2.036800e+04,3.797000e+03,1.730000e+03,1.739000e+03,6.000000e+00,1.900000e+01,1.752000e+03,1.908000e+03,9.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.700000e+01,1.900000e+01,1.000000e+00,2.022000e+03,9.000000e+00,2.300000e+01
max,2023-08-31 00:00:00,2.045200e+04,9.562000e+03,2.359000e+03,2.400000e+03,2.966000e+03,1.840000e+02,2.400000e+03,2.400000e+03,2.490000e+02,...,1.653000e+03,1.741000e+03,1.185000e+03,2.557000e+03,2.300000e+01,2.400000e+01,1.000000e+00,2.023000e+03,1.200000e+01,3.100000e+01
std,NaN,3.772846e+02,1.747258e+03,4.858789e+02,4.993101e+02,4.863687e+01,9.192901e+00,5.008727e+02,5.272368e+02,6.269639e+00,...,1.375707e+01,1.486748e+01,1.512105e+00,2.546245e+01,4.835019e+00,5.112877e+00,4.687655e-01,1.414654e+00,3.377382e+00,8.780096e+00

**Duplicate Check**

In [ ]:
df[df.duplicated()].shape     #  Duplicate records were checked to ensure data consistency.

(0, 40)

These missing values occur mainly due to cancelled or diverted flights, where departure or arrival information is not available.

# Missing Values Analysis

In [ ]:
df.isnull().sum()  #  Several columns contain missing values, particularly time-related columns and delay-related columns

FL_DATE                          0
AIRLINE                          0
AIRLINE_DOT                      0
AIRLINE_CODE                     0
DOT_CODE                         0
FL_NUMBER                        0
ORIGIN                           0
ORIGIN_CITY                      0
DEST                             0
DEST_CITY                        0
CRS_DEP_TIME                     0
DEP_TIME                     77615
DEP_DELAY                    77644
TAXI_OUT                     78806
WHEELS_OFF                   78806
WHEELS_ON                    79944
TAXI_IN                      79944
CRS_ARR_TIME                     0
ARR_TIME                     79942
ARR_DELAY                    86198
CANCELLED                        0
CANCELLATION_CODE          2920860
DIVERTED                         0
CRS_ELAPSED_TIME                14
ELAPSED_TIME                 86198
AIR_TIME                     86198
DISTANCE                         0
DELAY_DUE_CARRIER          2466137
DELAY_DUE_WEATHER          2466137
DELAY_DUE_NAS              2466137
DELAY_DUE_SECURITY         2466137
DELAY_DUE_LATE_AIRCRAFT    2466137
dtype: int64

**Handle Delay Columns**

In [ ]:
# These columns should be 0 if no delay:

delay = [
    'DEP_DELAY', 'ARR_DELAY',
    'DELAY_DUE_CARRIER', 'DELAY_DUE_WEATHER',
    'DELAY_DUE_NAS', 'DELAY_DUE_SECURITY',
    'DELAY_DUE_LATE_AIRCRAFT'
]

for col in delay:
    df[col] = df[col].fillna(0)

Missing values in delay columns were replaced with 0 because absence of delay indicates zero delay minutes.

**Handle Cancellation Code**

In [ ]:
df['CANCELLATION_CODE'] = df['CANCELLATION_CODE'].fillna('Not Cancelled')

Flights that were not cancelled were labeled as "Not Cancelled".

**Time Columns**

In [ ]:
# Flights that are cancelled will have missing times.

# We DO NOT fill them with 0.
# Instead we keep them as NaN

time= [
    'DEP_TIME', 'ARR_TIME',
    'TAXI_OUT', 'TAXI_IN',
    'WHEELS_OFF', 'WHEELS_ON',
    'ELAPSED_TIME', 'AIR_TIME'
]

df[time] = df[time].copy()

**Convert Data Types Properly**

In [ ]:
# Convert categorical columns
cat_cols = ['AIRLINE_CODE', 'ORIGIN', 'DEST', 'ORIGIN_CITY', 'DEST_CITY']

for col in cat_cols:
    df[col] = df[col].astype('category')

#  Convert numeric small integers:
df['CANCELLED'] = df['CANCELLED'].astype('int8')
df['DIVERTED'] = df['DIVERTED'].astype('int8')

**Feature Engineering**

In [ ]:
# Departure Hour
df['DEP_HOUR'] = (df['CRS_DEP_TIME'] // 100).astype('int')

In [ ]:
# Arrival Hour
df['ARR_HOUR'] = (df['CRS_ARR_TIME'] // 100).astype('int')

Departure and arrival hours were extracted to analyze time-based flight patterns

In [ ]:
# Create Route
df['ROUTE'] = df['ORIGIN'].astype(str) + '-' + df['DEST'].astype(str)

A route column was created to identify flight origin-destination pairs.

In [ ]:
# Delay Flag
df['IS_DELAYED'] = np.where(df['ARR_DELAY'] > 0, 1, 0)

A binary column was created to identify delayed flights.

In [ ]:
# KPI Metrics
total_flights = df['FL_NUMBER'].count()
unique_airlines = df['AIRLINE'].nunique()
avg_delay = df['ARR_DELAY'].mean()

print(total_flights, unique_airlines, avg_delay)

3000000 18 4.138432333333333

These KPIs provide a quick overview of airline operations and delay patterns.

**Convert to datetime**

In [ ]:
# Convert to datetime
df['FL_DATE'] = pd.to_datetime(df['FL_DATE'])

# Extract useful features
df['YEAR'] = df['FL_DATE'].dt.year
df['MONTH'] = df['FL_DATE'].dt.month
df['DAY'] = df['FL_DATE'].dt.day
df['DAY_OF_WEEK'] = df['FL_DATE'].dt.day_name()

**Final Check**

In [ ]:
df.head()
df.isnull().sum()

FL_DATE                          0
AIRLINE                          0
AIRLINE_DOT                      0
AIRLINE_CODE                     0
DOT_CODE                         0
FL_NUMBER                        0
ORIGIN                           0
ORIGIN_CITY                      0
DEST                             0
DEST_CITY                        0
CRS_DEP_TIME                     0
DEP_TIME                     77615
DEP_DELAY                        0
TAXI_OUT                     78806
WHEELS_OFF                   78806
WHEELS_ON                    79944
TAXI_IN                      79944
CRS_ARR_TIME                     0
ARR_TIME                     79942
ARR_DELAY                        0
CANCELLED                        0
CANCELLATION_CODE          2920860
DIVERTED                         0
CRS_ELAPSED_TIME                14
ELAPSED_TIME                 86198
AIR_TIME                     86198
DISTANCE                         0
DELAY_DUE_CARRIER                0
DELAY_DUE_WEATHER                0
DELAY_DUE_NAS                    0
DELAY_DUE_SECURITY               0
DELAY_DUE_LATE_AIRCRAFT          0
DEP_HOUR                         0
ARR_HOUR                         0
ROUTE                            0
IS_DELAYED                       0
YEAR                             0
MONTH                            0
DAY                              0
DAY_OF_WEEK                      0
dtype: int64

**Save Cleaned Dataset**

In [ ]:
df.to_csv('/content/airline_data.csv', index=False)

In [ ]:
# checking

import os
os.listdir("/content")

['.config',
 'cleaned_airline_data.csv',
 'drive',
 'airline_data.csv',
 'sample_data']

**Duplicate Check**

In [ ]:
df.duplicated().sum()

np.int64(0)

No duplicate records were found in the dataset.

**KPI Section**

In [ ]:
total_flights = df.shape[0]
unique_airlines = df['AIRLINE'].nunique()
avg_arrival_delay = df['ARR_DELAY'].mean()
cancelled_flights = df['CANCELLED'].sum()
avg_distance = df['DISTANCE'].mean()

print("Total Flights:", total_flights)
print("Unique Airlines:", unique_airlines)
print("Average Arrival Delay:", avg_arrival_delay)
print("Cancelled Flights:", cancelled_flights)
print("Average Flight Distance:", avg_distance)

Total Flights: 3000000
Unique Airlines: 18
Average Arrival Delay: 4.138432333333333
Cancelled Flights: 79140
Average Flight Distance: 809.3615516666666

KPI Insights:

Example:

The dataset contains approximately 3 million flights operated by multiple airlines.
The average arrival delay indicates the overall operational efficiency of airlines.
Cancellation statistics help identify reliability issues in airline operations.

In [ ]:
# Downloading Files

from google.colab import files
files.download('/content/airline_data.csv')

# Final Summary

## Preprocessing Summary

The dataset was successfully cleaned and prepared for further analysis.

Steps performed:
1. Loaded the airline dataset
2. Explored dataset structure and missing values
3. Handled delay and cancellation columns
4. Created date and time features
5. Generated route and delay indicators
6. Saved the cleaned dataset

The dataset is now ready for visual exploration and delay trend analysis in Milestone 2.