In [ ]:
# Install Required Libraries
!pip install plotly --quiet

In [ ]:
#Import Required Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

sns.set_style("whitegrid")
pd.set_option("display.max_columns", None)

In [ ]:
#Data Upload
from google.colab import files
uploaded = files.upload()

Saving airlines_flights_data.csv to airlines_flights_data.csv

**Load Dataset**

In [ ]:
df = pd.read_csv("airlines_flights_data.csv")
df.head()

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955

Initial Data Exploration:

Reading shape of **dataset**

In [ ]:
df.shape

(300153, 12)

Data Types & Structure

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300153 entries, 0 to 300152
Data columns (total 12 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   index             300153 non-null  int64
 1   airline           300153 non-null  object
 2   flight            300153 non-null  object
 3   source_city       300153 non-null  object
 4   departure_time    300153 non-null  object
 5   stops             300153 non-null  object
 6   arrival_time      300153 non-null  object
 7   destination_city  300153 non-null  object
 8   class             300153 non-null  object
 9   duration          300153 non-null  float64
 10  days_left         300153 non-null  int64
 11  price             300153 non-null  int64
dtypes: float64(1), int64(3), object(8)
memory usage: 27.5+ MB

In [ ]:
#statiscal summary
df.describe()

               index       duration      days_left          price
count  300153.000000  300153.000000  300153.000000  300153.000000
mean   150076.000000      12.221021      26.004751   20889.660523
std     86646.852011       7.191997      13.561004   22697.767366
min         0.000000       0.830000       1.000000    1105.000000
25%     75038.000000       6.830000      15.000000    4783.000000
50%    150076.000000      11.250000      26.000000    7425.000000
75%    225114.000000      16.170000      38.000000   42521.000000
max    300152.000000      49.830000      49.000000  123071.000000

In [ ]:
#Handling missing values

In [ ]:
df.isnull().sum().sort_values(ascending=False)

index               0
airline             0
flight              0
source_city         0
departure_time      0
stops               0
arrival_time        0
destination_city    0
class               0
duration            0
days_left           0
price               0
dtype: int64

Data Cleaning

In [ ]:
# Drop Unnecessary Index Column
df = df.drop(columns=['index'])

**Convert Categorical Columns**

In [ ]:
categorical_cols = [
    'airline', 'flight', 'source_city',
    'departure_time', 'stops',
    'arrival_time', 'destination_city', 'class'
]

for col in categorical_cols:
    df[col] = df[col].astype('category')

**Convert Duration to Numeric**

In [ ]:
df['duration'] = pd.to_numeric(df['duration'], errors='coerce')

Remove Duplicates

In [ ]:
df = df.drop_duplicates()

4.Feature Engineering
Create Route Column

In [ ]:
df['route'] = df['source_city'].astype(str) + " → " + df['destination_city'].astype(str)

**Convert days_left into Booking Urgency Category**

In [ ]:
df['booking_type'] = pd.cut(
    df['days_left'],
    bins=[0, 7, 30, 60, 365],
    labels=['Last_Minute', 'Short_Term', 'Mid_Term', 'Long_Term']
)

In [ ]:
#Save Cleaned Data
df.to_csv("airfly_cleaned_data.csv", index=False)